name: Build Blazefetch ARM64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]

    strategy:
      matrix:
        arch: [arm64]
        compiler: [gcc, clang]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ gcc clang \
            libx11-dev libxrandr-dev libasound2-dev libcurl4-openssl-dev

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          export CXX=g++
          export CC=gcc
        else
          export CXX=clang++
          export CC=clang
        fi
        cmake ../src -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.arch }}
      
    - name: Build
      run: |
        cd build
        make

    - name: Test executables
      run: |
        cd build/bin
        ./blazefetch --version
        ./blazefetch_iconic --version

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: blazefetch-${{ matrix.arch }}-${{ matrix.compiler }}
        path: build/bin/
